"""Import Garment model to app

Revision ID: 275b3c97f459
Revises: 
Create Date: 2022-07-26 15:50:13.076944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275b3c97f459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('street_size', sa.Integer(), nullable=False),
    sa.Column('label_size', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garment')
    # ### end Alembic commands ###
