"""Add create_instance_from_json method to Garment Model

Revision ID: 385d5cb926d4
Revises: 275b3c97f459
Create Date: 2022-07-26 16:25:01.132394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385d5cb926d4'
down_revision = '275b3c97f459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('garment', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('garment', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
