"""Remove image_file

Revision ID: bec6580e0223
Revises: d976402655e9
Create Date: 2022-08-11 20:22:16.585577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec6580e0223'
down_revision = 'd976402655e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garment', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garment', sa.Column('image_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
