"""Adds image_file column to Garment model

Revision ID: d976402655e9
Revises: f451a24cfa32
Create Date: 2022-08-10 21:42:48.656720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd976402655e9'
down_revision = 'f451a24cfa32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garment', sa.Column('image_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garment', 'image_file')
    # ### end Alembic commands ###
